coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
comment:                  # this is a top-level key
  layout: "header, reach, diff, flags, files" # add "condensed_" to "header", "files" and "footer"
  behavior: default
  hide_project_coverage: true # [true :: only show coverage on the git diff]
ignore:
  - "graph/generated.go" 
