version: '3'
services:
  graphql:
    build:
      context: .
      dockerfile: Dockerfile.graph
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://yourusername:yourpassword@db:5432/yourdatabase?sslmode=disable
      - AUDIENCE_API=https://shrektionary.com/api
      - AUDIENCE_HASH=4W01gsxupS4xoLLxbe8jdVVlGTFOKjd3
      - ENVIRONMENT=dev
      - ISSUERURL=https://dev-afmzazq3cr35ktpl.us.auth0.com/
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=yourusername
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdatabase
  db-migration:
    image: postgres
    restart: always
    ports:
      - '5431:5432'
    environment:
      - POSTGRES_USER=yourusername
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=migration
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: yourusername@gmail.com
      PGADMIN_DEFAULT_PASSWORD: yourpassword