FROM golang:1.21.4-alpine AS dependencies

WORKDIR /app

# Install build dependencies
RUN apk --no-cache add build-base && CGO_ENABLED=1

# Copy the go.mod and go.sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

FROM golang:1.21.4-alpine AS builder

WORKDIR /app

COPY --from=dependencies /app/go.mod /app/go.sum ./
COPY --from=dependencies $GOCACHE $GOCACHE
COPY --from=dependencies $GOPATH/pkg/mod $GOPATH/pkg/mod

# Copy the current directory contents into the container at /app
COPY . .

# Run tests using gotestsum
CMD [ "go", "test", "-p", "1", "-covermode=atomic", "./..." ]


