version: '3'
services:
  graphql:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://yourusername:yourpassword@db:5432/yourdatabase?sslmode=disable
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=yourusername
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdatabase
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: yourusername@gmail.com
      PGADMIN_DEFAULT_PASSWORD: yourpassword