package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"groupinary/ent"
	"groupinary/utils"

	"entgo.io/contrib/entgql"
)

// CurrentUser is the resolver for the currentUser field.
func (r *queryResolver) CurrentUser(ctx context.Context) (*ent.User, error) {
	creatorID, err := utils.GetCreatorIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	return r.client.User.Get(ctx, creatorID)
}

// DefinitionsConnections is the resolver for the definitionsConnections field.
func (r *queryResolver) DefinitionsConnections(ctx context.Context, wordID *int, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, orderBy *ent.DefinitionOrder, where *ent.DefinitionWhereInput) (*ent.DefinitionConnection, error) {
	return r.client.Definition.Query().
		Paginate(ctx, after, first, before, last,
			ent.WithDefinitionOrder(ent.DefaultDefinitionOrder),
			ent.WithDefinitionFilter(where.Filter),
			ent.WithDefinitionOrder(orderBy),
		)
}
