// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"shrektionary_api/ent/predicate"
	"shrektionary_api/ent/wordconnections"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WordConnectionsDelete is the builder for deleting a WordConnections entity.
type WordConnectionsDelete struct {
	config
	hooks    []Hook
	mutation *WordConnectionsMutation
}

// Where appends a list predicates to the WordConnectionsDelete builder.
func (wcd *WordConnectionsDelete) Where(ps ...predicate.WordConnections) *WordConnectionsDelete {
	wcd.mutation.Where(ps...)
	return wcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (wcd *WordConnectionsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, wcd.sqlExec, wcd.mutation, wcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (wcd *WordConnectionsDelete) ExecX(ctx context.Context) int {
	n, err := wcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (wcd *WordConnectionsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(wordconnections.Table, sqlgraph.NewFieldSpec(wordconnections.FieldID, field.TypeInt))
	if ps := wcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, wcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	wcd.mutation.done = true
	return affected, err
}

// WordConnectionsDeleteOne is the builder for deleting a single WordConnections entity.
type WordConnectionsDeleteOne struct {
	wcd *WordConnectionsDelete
}

// Where appends a list predicates to the WordConnectionsDelete builder.
func (wcdo *WordConnectionsDeleteOne) Where(ps ...predicate.WordConnections) *WordConnectionsDeleteOne {
	wcdo.wcd.mutation.Where(ps...)
	return wcdo
}

// Exec executes the deletion query.
func (wcdo *WordConnectionsDeleteOne) Exec(ctx context.Context) error {
	n, err := wcdo.wcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{wordconnections.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (wcdo *WordConnectionsDeleteOne) ExecX(ctx context.Context) {
	if err := wcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
