// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"shrektionary_api/ent/wordconnections"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// WordConnections is the model entity for the WordConnections schema.
type WordConnections struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Description holds the value of the "description" field.
	Description  string `json:"description,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WordConnections) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case wordconnections.FieldID:
			values[i] = new(sql.NullInt64)
		case wordconnections.FieldDescription:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WordConnections fields.
func (wc *WordConnections) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case wordconnections.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			wc.ID = int(value.Int64)
		case wordconnections.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				wc.Description = value.String
			}
		default:
			wc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WordConnections.
// This includes values selected through modifiers, order, etc.
func (wc *WordConnections) Value(name string) (ent.Value, error) {
	return wc.selectValues.Get(name)
}

// Update returns a builder for updating this WordConnections.
// Note that you need to call WordConnections.Unwrap() before calling this method if this WordConnections
// was returned from a transaction, and the transaction was committed or rolled back.
func (wc *WordConnections) Update() *WordConnectionsUpdateOne {
	return NewWordConnectionsClient(wc.config).UpdateOne(wc)
}

// Unwrap unwraps the WordConnections entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (wc *WordConnections) Unwrap() *WordConnections {
	_tx, ok := wc.config.driver.(*txDriver)
	if !ok {
		panic("ent: WordConnections is not a transactional entity")
	}
	wc.config.driver = _tx.drv
	return wc
}

// String implements the fmt.Stringer.
func (wc *WordConnections) String() string {
	var builder strings.Builder
	builder.WriteString("WordConnections(")
	builder.WriteString(fmt.Sprintf("id=%v, ", wc.ID))
	builder.WriteString("description=")
	builder.WriteString(wc.Description)
	builder.WriteByte(')')
	return builder.String()
}

// WordConnectionsSlice is a parsable slice of WordConnections.
type WordConnectionsSlice []*WordConnections
