// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Definition is the predicate function for definition builders.
type Definition func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// Word is the predicate function for word builders.
type Word func(*sql.Selector)
